on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 1 * *"

name: run_scripts

jobs:
  run_scripts:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - name: Get ADMIXTURE
        run: ./get_admixture.sh

      - name: Run ADMIXTURE example
        run: ./admixture hapmap3.bed 3

