on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 1 * *"

name: run_scripts

jobs:
  run_scripts:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - name: Get ADMIXTURE
        run: ./get_admixture.sh

      - name: Run ADMIXTURE example
        run: ./admixture hapmap3.bed 3

      - name: Move the P file
        run: mv hapmap3.3.P hapmap3_block.3.P

      - name: Move the Q file
        run: mv hapmap3.3.P hapmap3_block.3.P

      - name: Show the head of the P file
        run: head hapmap3_block.3.P

      - name: Show the head of the Q file
        run: head hapmap3_block.3.P

      - name: Run ADMIXTURE example with EM method
        run: ./admixture hapmap3.bed 3 -m EM

      - name: Move the P file
        run: mv hapmap3.3.P hapmap3_em.3.P

      - name: Move the Q file
        run: mv hapmap3.3.P hapmap3_em.3.P

      - name: Show the head of the P file
        run: head hapmap3_em.3.P

      - name: Show the head of the Q file
        run: head hapmap3_em.3.P

      - name: Zip the Q and P files
        run: zip admixture_results.zip *.P *.Q

      - name: Upload table to the workflow tab
        uses: actions/upload-artifact@v2
        with:
          name: admixture_results
          path: admixture_results.zip

