on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 1 * *"

name: run_scripts

jobs:
  run_scripts:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Get ADMIXTURE
        run: ./get_admixture.sh

      - name: Run ADMIXTURE
        run: ./run_admixture.sh

      - name: Install R
        uses: r-lib/actions/setup-r@v1

      - name: Install dependencies
        run: |
          install.packages("remotes", "readr")
          remotes::install_github("royfrancis/pophelper")
        shell: Rscript {0}

      - name: Create pictures
        run: Rscript plot_results.R

      - name: Zip the Q, P and PNG files
        run: zip admixture_results.zip *.P *.Q *.png

      - name: Upload table to the workflow tab
        uses: actions/upload-artifact@v2
        with:
          name: admixture_results
          path: admixture_results.zip

