on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 1 * *"

name: run_scripts

jobs:
  run_scripts:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - name: Get ADMIXTURE
        run: ./get_admixture.sh

      - name: Run ADMIXTURE example
        run: ./admixture hapmap3.bed 3

      - name: Show P file
        run: cat *.P

      - name: Show Q file
        run: cat *.Q

      - name: Zip the Q and P files
        run: zip admixture_results.zip *.P *.Q

      - name: Upload table to the workflow tab
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: results.zip

